env: "local"
rest:
  port: 8090
  timeout: 5s
grpc:
  user: "localhost:50051"
  organization: "localhost:50052"
  product: "localhost:50053"
  crm: "localhost:50054"
  warehouse: "localhost:50055"
  order: "localhost:50056"
  advertisement: "localhost:50057"
  customer: localhost:50058
  service: localhost:50059
