name: CI/CD for Core Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy Core Service
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t arsen2group/core-service:latest .
          docker push arsen2group/core-service:latest

      # 4. SSH into VPS, Update Config and Restart Container
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Stop and remove the existing container
            docker stop core-service || true
            docker rm core-service || true

            # Pull the latest image from Docker Hub
            docker pull arsen2group/core-service:latest

            # Prune old images to save space
            docker image prune -f

            # Run the updated container with volume mounting for config.yaml
            docker run -d \
              --name core-service \
              --network app-network \
              -v /home/2sales/core-service/server.yaml:/app/config/server.yaml \
              -p 8090:8090 \
              arsen2group/core-service:latest